# Generated by Django 5.0.6 on 2026-06-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incentive',
            unique_together={('employee', 'rule', 'month', 'year')},
        ),
    ]
