# Generated by Django 5.0.6 on 2026-06-26 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_incentive_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=80)),
                ('level_order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['level_order'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='hierarchy_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.hierarchylevel'),
        ),
    ]
