# Generated by Django 5.0.6 on 2026-06-29 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_seed_cost_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('level', 'Hierarchy Level'), ('employee', 'Employee')], default='global', max_length=20)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multipliers', to='hr.employee')),
                ('hierarchy_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multipliers', to='hr.hierarchylevel')),
            ],
        ),
    ]
