# Generated by Django 5.0.6 on 2026-06-30 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_seed_target_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('level', 'Hierarchy Level')], default='global', max_length=20)),
                ('revenue_weight', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('growth_weight', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('activity_weight', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('hierarchy_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perf_weights', to='hr.hierarchylevel')),
            ],
        ),
    ]
