# Generated by Django 5.0.6 on 2026-06-30 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_seed_metrics'),
        ('hr', '0011_seed_performance_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('min_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('max_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('incentive_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('basis', models.CharField(choices=[('revenue', '% of revenue generated'), ('target', '% of target value')], default='revenue', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['min_pct'],
            },
        ),
        migrations.CreateModel(
            name='ActivityIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_count', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='crm.metricdefinition')),
            ],
        ),
    ]
