# Generated by Django 5.0.6 on 2026-06-30 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_seed_incentive_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('match', models.CharField(choices=[('all', 'Match ALL (AND)'), ('any', 'Match ANY (OR)')], default='all', max_length=4)),
                ('payout_type', models.CharField(choices=[('percent', 'Percent of'), ('flat', 'Flat amount'), ('per_unit', 'Per unit of')], default='percent', max_length=10)),
                ('payout_on', models.CharField(blank=True, max_length=40)),
                ('payout_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormulaCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.CharField(max_length=40)),
                ('operator', models.CharField(choices=[('gt', '>'), ('gte', '≥'), ('lt', '<'), ('lte', '≤'), ('eq', '='), ('between', 'between')], default='gt', max_length=10)),
                ('right_type', models.CharField(choices=[('constant', 'Constant'), ('variable', 'Variable')], default='constant', max_length=10)),
                ('right_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('right_value2', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('right_variable', models.CharField(blank=True, max_length=40)),
                ('right_factor', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='hr.formularule')),
            ],
        ),
    ]
