# Generated by Django 5.0.6 on 2026-07-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_seed_formula_rules'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incentive',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='incentive',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual / Rule'), ('slab', 'Incentive slab'), ('formula', 'Formula')], default='manual', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='incentive',
            unique_together={('employee', 'rule', 'source', 'month', 'year')},
        ),
    ]
