# Generated by Django 5.0.6 on 2026-07-25 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_role_derived_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('audience', models.CharField(blank=True, max_length=120)),
                ('delivery_mode', models.CharField(blank=True, max_length=60)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('mandatory', models.BooleanField(default=True)),
                ('frequency', models.CharField(blank=True, max_length=40)),
                ('pass_mark', models.DecimalField(decimal_places=2, default=0.8, max_digits=5)),
                ('content_summary', models.TextField(blank=True)),
                ('learning_outcome', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_trainings', to='hr.employee')),
            ],
            options={
                'ordering': ['module_id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_assigned', 'Not Assigned'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('exempted', 'Exempted')], default='assigned', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('latest_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('certificate_expiry', models.DateField(blank=True, null=True)),
                ('manager_comment', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_assignments', to='hr.employee')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr.trainingmodule')),
            ],
            options={
                'ordering': ['-assigned_date', 'employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pass_mark', models.DecimalField(decimal_places=2, default=0.8, max_digits=5)),
                ('result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('knowledge_gap', models.CharField(blank=True, max_length=200)),
                ('retest_due', models.DateField(blank=True, null=True)),
                ('certificate_id', models.CharField(blank=True, max_length=40)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed', to='hr.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='hr.employee')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='hr.trainingmodule')),
            ],
            options={
                'ordering': ['-assessment_date', 'employee_id'],
            },
        ),
    ]
