// Single source of truth for every CRUD module.
// `columns` -> table; `fields` -> create/edit form.
// field types: text, number, email, date, datetime-local, textarea, select, ref, creatable
// ref fields load options from another endpoint (labelKey shown to user).
import { COUNTRY_OPTIONS } from "./countries";

export const STATUS_COLORS = {
  active: "bg-emerald-50 text-emerald-700",
  inactive: "bg-ink-100 text-ink-600",
  new: "bg-blue-50 text-blue-700",
  contacted: "bg-amber-50 text-amber-700",
  qualified: "bg-violet-50 text-violet-700",
  converted: "bg-emerald-50 text-emerald-700",
  lost: "bg-rose-50 text-rose-700",
  won: "bg-emerald-50 text-emerald-700",
  open: "bg-blue-50 text-blue-700",
  closed: "bg-ink-100 text-ink-600",
  proposal: "bg-amber-50 text-amber-700",
  negotiation: "bg-violet-50 text-violet-700",
  draft: "bg-ink-100 text-ink-600",
  sent: "bg-blue-50 text-blue-700",
  accepted: "bg-emerald-50 text-emerald-700",
  revised: "bg-amber-50 text-amber-700",
  expired: "bg-ink-100 text-ink-500",
  pending: "bg-amber-50 text-amber-700",
  approved: "bg-emerald-50 text-emerald-700",
  rejected: "bg-rose-50 text-rose-700",
  resolved: "bg-emerald-50 text-emerald-700",
  assigned: "bg-blue-50 text-blue-700",
  in_progress: "bg-violet-50 text-violet-700",
  present: "bg-emerald-50 text-emerald-700",
  absent: "bg-rose-50 text-rose-700",
  urgent: "bg-rose-50 text-rose-700",
  high: "bg-amber-50 text-amber-700",
  medium: "bg-blue-50 text-blue-700",
  low: "bg-ink-100 text-ink-600",
  // product revenue types
  one_time: "bg-blue-50 text-blue-700",
  recurring: "bg-violet-50 text-violet-700",
  per_unit: "bg-amber-50 text-amber-700",
  token: "bg-emerald-50 text-emerald-700",
  // KPI metric (PART 6) — category / aggregation / source
  growth: "bg-emerald-50 text-emerald-700",
  activity: "bg-blue-50 text-blue-700",
  other: "bg-ink-100 text-ink-600",
  sum: "bg-violet-50 text-violet-700",
  count: "bg-blue-50 text-blue-700",
  average: "bg-amber-50 text-amber-700",
  latest: "bg-cyan-50 text-cyan-700",
  manual: "bg-ink-100 text-ink-600",
  derived: "bg-violet-50 text-violet-700",
  // AUM (PART 11)
  deposit: "bg-emerald-50 text-emerald-700",
  withdrawal: "bg-rose-50 text-rose-700",
};

const sel = (...opts) => opts.map((o) => ({ value: o, label: o[0].toUpperCase() + o.slice(1).replace("_", " ") }));

// A user and an employee are the same person, so Administration → Users and
// HR → People share ONE form. Both endpoints accept every field below: the login
// half (email/password/status) and the HR half (level/manager/salary) are saved
// together whichever page you add the person from.
const PERSON_FIELDS = [
  { key: "name", label: "Name", required: true },
  { key: "email", label: "Email", type: "email", required: true },
  { key: "employee_id", label: "Employee ID" },
  { key: "phone", label: "Phone" },
  // Role drives the org level — pick the role and the level follows, so there is
  // no "Org Level" field to keep in step with it.
  { key: "role", label: "Role", type: "ref", ref: "roles", labelKey: "name" },
  { key: "manager", label: "Reports to (manager)", type: "ref", ref: "users/assignable", labelKey: "name" },
  { key: "department", label: "Department", type: "ref", ref: "departments", labelKey: "department_name" },
  { key: "salary", label: "Salary (monthly)", type: "number" },
  { key: "joining_date", label: "Joining date", type: "date" },
  { key: "status", label: "Status", type: "select", options: sel("active", "inactive", "suspended") },
  { key: "password", label: "Password (set/reset)", type: "text" },
];

export const RESOURCES = {
  users: {
    title: "Users", endpoint: "users", search: true,
    columns: [
      { key: "employee_id", label: "Emp ID" },
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "role_name", label: "Role" },
      { key: "hierarchy_level_name", label: "Level" },
      { key: "manager_name", label: "Reports to" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: PERSON_FIELDS,
  },
  roles: {
    title: "Roles", endpoint: "roles",
    columns: [{ key: "name", label: "Role" }, { key: "description", label: "Description" }],
    fields: [{ key: "name", label: "Name", required: true }, { key: "description", label: "Description", type: "textarea" }],
  },
  "hierarchy-levels": {
    title: "Hierarchy Levels", endpoint: "hierarchy-levels", search: true,
    columns: [
      { key: "level_order", label: "Order" },
      { key: "level_name", label: "Level" },
      { key: "employee_count", label: "Employees" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "level_name", label: "Level name (e.g. Country Head, RM)", required: true },
      { key: "level_order", label: "Order (1 = top of org)", type: "number", required: true },
      { key: "status", label: "Status", type: "select", options: sel("active", "inactive") },
    ],
  },
  "cost-categories": {
    title: "Cost Categories", endpoint: "cost-categories", search: true,
    columns: [
      { key: "name", label: "Category" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "name", label: "Category name (e.g. Visa, Desk, Internet)", required: true },
      { key: "status", label: "Status", type: "select", options: sel("active", "inactive") },
    ],
  },
  "employee-costs": {
    title: "Employee Costs", endpoint: "employee-costs", search: false,
    filters: [
      { key: "employee", label: "Employee", ref: "employees", labelKey: "user_name" },
      { key: "category", label: "Category", ref: "cost-categories", labelKey: "name" },
    ],
    columns: [
      { key: "employee_name", label: "Employee" },
      { key: "category_name", label: "Category" },
      { key: "amount", label: "Amount (monthly)", money: true },
      { key: "month", label: "Month" },
      { key: "year", label: "Year" },
    ],
    fields: [
      { key: "employee", label: "Employee", type: "ref", ref: "employees", labelKey: "user_name", required: true },
      { key: "category", label: "Cost category", type: "ref", ref: "cost-categories", labelKey: "name", required: true },
      { key: "amount", label: "Amount (this month's figure)", type: "number", required: true },
      { key: "month", label: "Month (1-12)", type: "number", required: true },
      { key: "year", label: "Year", type: "number", required: true },
    ],
  },
  teams: {
    title: "Teams", endpoint: "teams", search: true,
    columns: [{ key: "name", label: "Team" }, { key: "leader_name", label: "Leader" }],
    fields: [
      { key: "name", label: "Team name", required: true },
      { key: "leader", label: "Leader", type: "ref", ref: "users", labelKey: "name" },
    ],
  },
  businesses: {
    title: "Businesses", endpoint: "businesses", search: true,
    columns: [
      { key: "name", label: "Business" },
      { key: "description", label: "Description" },
      { key: "product_count", label: "Products" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "name", label: "Business name", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: sel("active", "inactive") },
    ],
  },
  products: {
    title: "Products", endpoint: "products", search: true,
    columns: [
      { key: "name", label: "Product" },
      { key: "business_name", label: "Business" },
      { key: "product_type", label: "Type" },
      { key: "price", label: "Price", money: true },
      { key: "revenue_type", label: "Revenue", badge: true },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "name", label: "Product name", required: true },
      { key: "business", label: "Business", type: "ref", ref: "businesses", labelKey: "name", required: true },
      { key: "product_type", label: "Type (e.g. Node, Coin, Subscription, Course)",
        type: "creatable", optionsFrom: { endpoint: "products", field: "product_type" } },
      { key: "price", label: "Price", type: "number" },
      { key: "revenue_type", label: "Revenue type", type: "select",
        options: [
          { value: "one_time", label: "One-Time Sale" },
          { value: "recurring", label: "Recurring / Subscription" },
          { value: "per_unit", label: "Per Unit (e.g. per GB)" },
          { value: "token", label: "Token Purchase" },
        ] },
      { key: "status", label: "Status", type: "select", options: sel("active", "inactive") },
    ],
  },
  "lead-sources": {
    title: "Lead Sources", endpoint: "lead-sources",
    columns: [{ key: "name", label: "Source" }],
    fields: [{ key: "name", label: "Source name", required: true }],
  },
  leads: {
    title: "Leads", endpoint: "leads", search: true, importable: true, detailPath: "/leads",
    distribute: { path: "leads/distribute" },
    filters: [
      { key: "status", label: "Status", options: sel("new", "contacted", "qualified", "converted", "lost") },
      { key: "source", label: "Source", ref: "lead-sources/social", labelKey: "name" },
    ],
    columns: [
      { key: "lead_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "phone", label: "Phone", adminOnly: true },
      { key: "country", label: "Country" },
      { key: "source_name", label: "Source" },
      { key: "assigned_name", label: "Owner" },
      { key: "score", label: "Score", score: true },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "lead_code", label: "Lead code", required: true },
      { key: "name", label: "Name", required: true },
      { key: "email", label: "Email", type: "email" },
      { key: "phone", label: "Phone" },
      { key: "country", label: "Country", type: "select", options: COUNTRY_OPTIONS, dialTo: "phone" },
      { key: "source", label: "Source", type: "ref", ref: "lead-sources/social", labelKey: "name" },
      { key: "assigned_to", label: "Assign to", type: "ref", ref: "users/assignable", labelKey: "name" },
      { key: "status", label: "Status", type: "select", options: sel("new", "contacted", "qualified", "converted", "lost") },
    ],
  },
  "lead-activities": {
    title: "Lead Activities", endpoint: "lead-activities", search: false,
    filters: [
      { key: "lead", label: "Lead", ref: "leads", labelKey: "name" },
      { key: "activity_type", label: "Type", options: sel("call", "whatsapp", "email", "meeting", "note", "proposal") },
    ],
    columns: [
      { key: "lead_name", label: "Lead" },
      { key: "activity_type", label: "Type", badge: true },
      { key: "remarks", label: "Remarks" },
      { key: "followup_date", label: "Follow-up" },
      { key: "user_name", label: "By" },
    ],
    fields: [
      { key: "lead", label: "Lead", type: "ref", ref: "leads", labelKey: "name", required: true },
      { key: "activity_type", label: "Type", type: "select", options: sel("call", "whatsapp", "email", "meeting", "note") },
      { key: "remarks", label: "Remarks", type: "textarea" },
      { key: "followup_date", label: "Follow-up date", type: "date" },
      { key: "next_action", label: "Next action" },
    ],
  },
  opportunities: {
    title: "Opportunities", endpoint: "opportunities", search: true,
    filters: [
      { key: "stage", label: "Stage", options: sel("proposal", "negotiation", "won", "lost", "active") },
      { key: "status", label: "Status", options: sel("open", "closed") },
    ],
    columns: [
      { key: "lead_name", label: "Lead" },
      { key: "product_name", label: "Product" },
      { key: "assigned_name", label: "Owner" },
      { key: "stage", label: "Stage", badge: true },
      { key: "expected_revenue", label: "Expected", money: true },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "lead", label: "Lead", type: "ref", ref: "leads", labelKey: "name", required: true },
      { key: "product", label: "Product", type: "ref", ref: "products", labelKey: "name" },
      { key: "assigned_to", label: "Owner", type: "ref", ref: "users", labelKey: "name" },
      { key: "stage", label: "Stage", type: "select", options: sel("proposal", "negotiation", "won", "lost", "active") },
      { key: "expected_revenue", label: "Expected revenue", type: "number" },
      { key: "status", label: "Status", type: "select", options: sel("open", "closed") },
    ],
  },
  customers: {
    title: "Customers", endpoint: "customers", search: true, detailPath: "/customers",
    columns: [
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "country", label: "Country" },
      { key: "assigned_name", label: "RM" },
    ],
    fields: [
      { key: "name", label: "Name", required: true },
      { key: "email", label: "Email", type: "email" },
      { key: "phone", label: "Phone" },
      { key: "country", label: "Country", type: "select", options: COUNTRY_OPTIONS, dialTo: "phone" },
    ],
  },
  communications: {
    title: "Communications", endpoint: "communications",
    filters: [
      { key: "lead", label: "Lead", ref: "leads", labelKey: "name" },
      { key: "customer", label: "Customer", ref: "customers", labelKey: "name" },
      { key: "channel", label: "Channel", options: sel("whatsapp", "email", "sms", "telegram") },
    ],
    columns: [
      { key: "contact", label: "Contact" },
      { key: "channel", label: "Channel", badge: true },
      { key: "direction", label: "Direction" },
      { key: "message", label: "Message" },
      { key: "created_at", label: "When", datetime: true },
    ],
    fields: [
      { key: "channel", label: "Channel", type: "select", options: sel("whatsapp", "email", "sms", "telegram") },
      { key: "direction", label: "Direction", type: "select", options: sel("outbound", "inbound") },
      { key: "lead", label: "Lead", type: "ref", ref: "leads", labelKey: "name" },
      { key: "customer", label: "Customer", type: "ref", ref: "customers", labelKey: "name" },
      { key: "message", label: "Message", type: "textarea" },
    ],
  },
  targets: {
    title: "Targets", endpoint: "targets", search: true,
    filters: [
      { key: "target_type", label: "Type", options: sel("revenue", "leads", "conversions") },
    ],
    columns: [
      { key: "name", label: "Target" },
      { key: "target_type", label: "Type", badge: true },
      { key: "value", label: "Target", money: true },
      { key: "achieved", label: "Achieved", money: true },
      { key: "progress_pct", label: "Progress", progress: true },
      { key: "business_name", label: "Business" },
      { key: "end_date", label: "Ends" },
    ],
    fields: [
      { key: "name", label: "Target name", required: true },
      { key: "target_type", label: "Type", type: "select", options: sel("revenue", "leads", "conversions") },
      { key: "value", label: "Value", type: "number" },
      { key: "business", label: "Business", type: "ref", ref: "businesses", labelKey: "name" },
      { key: "start_date", label: "Start date", type: "date", required: true },
      { key: "end_date", label: "End date", type: "date", required: true },
    ],
  },
  revenues: {
    title: "Revenue", endpoint: "revenues", search: true,
    columns: [
      { key: "customer_name", label: "Customer" },
      { key: "business_name", label: "Business" },
      { key: "gross_revenue", label: "Gross", money: true },
      { key: "commission", label: "Commission", money: true },
      { key: "net_revenue", label: "Net", money: true },
      { key: "created_at", label: "Date", datetime: true },
    ],
    fields: [
      { key: "customer", label: "Customer", type: "ref", ref: "customers", labelKey: "name", required: true },
      { key: "business", label: "Business", type: "ref", ref: "businesses", labelKey: "name" },
      { key: "product", label: "Product", type: "ref", ref: "products", labelKey: "name", dependsOn: "business" },
      { key: "gross_revenue", label: "Gross revenue", type: "number", required: true },
      { key: "commission", label: "Commission", type: "number" },
    ],
  },
  tickets: {
    title: "Support Tickets", endpoint: "tickets", search: true, detailPath: "/tickets",
    filters: [
      { key: "status", label: "Status", options: sel("open", "assigned", "in_progress", "resolved", "closed") },
      { key: "priority", label: "Priority", options: sel("low", "medium", "high", "urgent") },
    ],
    columns: [
      { key: "ticket_no", label: "Ticket #" },
      { key: "customer_name", label: "Customer" },
      { key: "category", label: "Category" },
      { key: "priority", label: "Priority", badge: true },
      { key: "assigned_name", label: "Agent" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "ticket_no", label: "Ticket no", required: true },
      { key: "customer", label: "Customer", type: "ref", ref: "customers", labelKey: "name" },
      { key: "category", label: "Category" },
      { key: "priority", label: "Priority", type: "select", options: sel("low", "medium", "high", "urgent") },
      { key: "assigned_to", label: "Agent", type: "ref", ref: "users", labelKey: "name" },
      { key: "status", label: "Status", type: "select", options: sel("open", "assigned", "in_progress", "resolved", "closed") },
    ],
  },
  departments: {
    title: "Departments", endpoint: "departments",
    columns: [{ key: "department_name", label: "Department" }],
    fields: [{ key: "department_name", label: "Department name", required: true }],
  },
  employees: {
    title: "Employees", endpoint: "employees", search: true,
    columns: [
      { key: "employee_id", label: "Emp ID" },
      { key: "user_name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "role_name", label: "Role" },
      { key: "hierarchy_level_name", label: "Level" },
      { key: "manager_name", label: "Reports to" },
      { key: "department_name", label: "Department" },
      { key: "salary", label: "Salary", money: true },
      { key: "monthly_ctc", label: "CTC (mo)", money: true },
      { key: "joining_date", label: "Joined" },
    ],
    fields: PERSON_FIELDS,   // same form as Administration → Users
  },
  attendance: {
    title: "Attendance", endpoint: "attendance",
    columns: [
      { key: "employee_name", label: "Employee" },
      { key: "date", label: "Date" },
      { key: "working_hours", label: "Hours" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "employee", label: "Employee", type: "ref", ref: "employees", labelKey: "user_name", required: true },
      { key: "date", label: "Date", type: "date", required: true },
      { key: "working_hours", label: "Working hours", type: "number" },
      { key: "status", label: "Status", type: "select", options: sel("present", "absent", "half_day", "leave") },
    ],
  },
  "employee-activities": {
    title: "Employee Activity", endpoint: "employee-activities",
    columns: [
      { key: "employee_name", label: "Employee" },
      { key: "date", label: "Date" },
      { key: "active_duration", label: "Active (min)" },
      { key: "calls_completed", label: "Calls" },
      { key: "tickets_updated", label: "Tickets" },
    ],
    fields: [
      { key: "employee", label: "Employee", type: "ref", ref: "employees", labelKey: "user_name", required: true },
      { key: "date", label: "Date", type: "date", required: true },
      { key: "login_duration", label: "Login (min)", type: "number" },
      { key: "active_duration", label: "Active (min)", type: "number" },
      { key: "idle_duration", label: "Idle (min)", type: "number" },
      { key: "calls_completed", label: "Calls", type: "number" },
      { key: "tickets_updated", label: "Tickets updated", type: "number" },
    ],
  },
  "leave-types": {
    title: "Leave Types", endpoint: "leave-types",
    columns: [{ key: "leave_name", label: "Leave type" }],
    fields: [{ key: "leave_name", label: "Leave type", required: true }],
  },
  leaves: {
    title: "Leaves", endpoint: "leaves",
    filters: [
      { key: "status", label: "Status", options: sel("pending", "approved", "rejected") },
    ],
    rowActions: [
      { label: "Approve", icon: "check", variant: "success", when: { status: "pending" }, post: (id) => `leaves/${id}/approve/` },
      { label: "Reject", icon: "x", variant: "danger", when: { status: "pending" }, post: (id) => `leaves/${id}/reject/` },
    ],
    columns: [
      { key: "employee_name", label: "Employee" },
      { key: "start_date", label: "From" },
      { key: "end_date", label: "To" },
      { key: "reason", label: "Reason" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "employee", label: "Employee", type: "ref", ref: "employees", labelKey: "user_name", required: true },
      { key: "leave_type", label: "Leave type", type: "ref", ref: "leave-types", labelKey: "leave_name" },
      { key: "start_date", label: "From", type: "date", required: true },
      { key: "end_date", label: "To", type: "date", required: true },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: sel("pending", "approved", "rejected") },
    ],
  },
  payrolls: {
    title: "Payroll", endpoint: "payrolls",
    // Auto-calculate basic/incentive/deduction when an employee (and month/year) is chosen.
    autofill: { endpoint: "payrolls/suggest", trigger: ["employee", "month", "year"],
                fills: ["basic_salary", "incentive", "bonus", "deduction", "month", "year"] },
    rowActions: [
      { label: "Payslip", icon: "download", variant: "info", download: (id) => `payrolls/${id}/payslip/` },
    ],
    columns: [
      { key: "employee_name", label: "Employee" },
      { key: "basic_salary", label: "Basic", money: true },
      { key: "incentive", label: "Incentive", money: true },
      { key: "bonus", label: "Bonus", money: true },
      { key: "deduction", label: "Deduction", money: true },
      { key: "final_salary", label: "Net Pay", money: true },
      { key: "month", label: "Month" },
      { key: "year", label: "Year" },
    ],
    fields: [
      { key: "employee", label: "Employee", type: "ref", ref: "employees", labelKey: "user_name", required: true },
      { key: "basic_salary", label: "Basic salary", type: "number" },
      { key: "incentive", label: "Incentive", type: "number" },
      { key: "bonus", label: "Bonus", type: "number" },
      { key: "deduction", label: "Deduction", type: "number" },
      { key: "month", label: "Month (1-12)", type: "number", required: true },
      { key: "year", label: "Year", type: "number", required: true },
    ],
  },
  "incentive-rules": {
    title: "Incentive Rules", endpoint: "incentive-rules",
    columns: [
      { key: "business_name", label: "Business" },
      { key: "product_name", label: "Product" },
      { key: "formula_type", label: "Type", badge: true },
      { key: "formula_value", label: "Value" },
    ],
    fields: [
      { key: "business", label: "Business", type: "ref", ref: "businesses", labelKey: "name", required: true },
      { key: "product", label: "Product", type: "ref", ref: "products", labelKey: "name", dependsOn: "business" },
      { key: "formula_type", label: "Formula type", type: "select", options: sel("percentage", "fixed", "slab") },
      { key: "formula_value", label: "Value", type: "number" },
    ],
  },
  incentives: {
    title: "Incentives", endpoint: "incentives",
    recalc: { path: "incentives/calculate", title: "Auto-Calculate Incentives" },
    filters: [],
    columns: [
      { key: "employee_name", label: "Employee" },
      { key: "amount", label: "Amount", money: true },
      { key: "month", label: "Month" },
      { key: "year", label: "Year" },
    ],
    fields: [
      { key: "employee", label: "Employee", type: "ref", ref: "employees", labelKey: "user_name", required: true },
      { key: "rule", label: "Rule", type: "ref", ref: "incentive-rules", labelKey: "label" },
      { key: "amount", label: "Amount", type: "number" },
      { key: "month", label: "Month (1-12)", type: "number", required: true },
      { key: "year", label: "Year", type: "number", required: true },
    ],
  },
  "metric-definitions": {
    title: "KPI Definitions", endpoint: "metric-definitions", search: true,
    columns: [
      { key: "name", label: "Metric" },
      { key: "business_name", label: "Business" },
      { key: "aggregation", label: "Aggregation", badge: true },
      { key: "category", label: "Category", badge: true },
      { key: "source", label: "Source", badge: true },
      { key: "unit", label: "Unit" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "name", label: "Metric name (e.g. Lots Traded, Nodes Sold, Meetings)", required: true,
        type: "creatable", optionsFrom: { endpoint: "metric-definitions", field: "name" } },
      { key: "business", label: "Business (blank = all)", type: "ref", ref: "businesses", labelKey: "name" },
      { key: "product", label: "Product (optional)", type: "ref", ref: "products", labelKey: "name", dependsOn: "business" },
      { key: "unit", label: "Unit ($, GB, count, lots)" },
      { key: "aggregation", label: "How to aggregate over a period", type: "select", options: sel("sum", "count", "average", "latest") },
      { key: "category", label: "Scorecard category", type: "select", options: sel("growth", "activity", "other") },
      { key: "source", label: "Source", type: "select", options: sel("manual", "derived") },
      { key: "derived_key", label: "Derived from (only if source = derived)", type: "select", options: [
        { value: "", label: "—" },
        { value: "lead_activity:meeting", label: "Meetings logged (Lead Activity)" },
        { value: "lead_activity:call", label: "Calls logged (Lead Activity)" },
        { value: "lead:converted", label: "Leads converted" },
      ] },
      { key: "status", label: "Status", type: "select", options: sel("active", "inactive") },
    ],
  },
  "metric-entries": {
    title: "KPI Entries", endpoint: "metric-entries",
    // For derived metrics (Calls, Meetings, Leads Converted) auto-fetch the value
    // from the employee's real CRM activity when metric/employee/date are chosen.
    autofill: { endpoint: "metric-entries/suggest", trigger: ["metric", "employee", "date"],
                fills: ["value"] },
    filters: [
      { key: "metric", label: "Metric", ref: "metric-definitions", labelKey: "name" },
      { key: "employee", label: "Employee", ref: "employees", labelKey: "user_name" },
      { key: "customer", label: "Trader", ref: "customers", labelKey: "name" },
    ],
    columns: [
      { key: "metric_name", label: "Metric" },
      { key: "employee_name", label: "Employee" },
      { key: "customer_name", label: "Trader" },
      { key: "value", label: "Value" },
      { key: "unit", label: "Unit" },
      { key: "date", label: "Date" },
      { key: "note", label: "Note" },
    ],
    fields: [
      { key: "metric", label: "Metric", type: "ref", ref: "metric-definitions", labelKey: "name", required: true },
      { key: "employee", label: "Employee", type: "ref", ref: "employees", labelKey: "user_name", required: true },
      { key: "value", label: "Value", type: "number", required: true },
      { key: "date", label: "Date", type: "date", required: true },
      { key: "note", label: "Note (optional)" },
    ],
  },
  "target-multipliers": {
    title: "Target Multipliers", endpoint: "target-multipliers",
    columns: [
      { key: "label", label: "Applies to" },
      { key: "scope", label: "Scope", badge: true },
      { key: "multiplier", label: "Multiplier (×)" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "scope", label: "Scope", type: "select", options: sel("global", "level", "employee"), required: true },
      { key: "hierarchy_level", label: "Hierarchy level (if scope = level)", type: "ref", ref: "hierarchy-levels", labelKey: "level_name" },
      { key: "employee", label: "Employee (if scope = employee)", type: "ref", ref: "employees", labelKey: "user_name" },
      { key: "multiplier", label: "Multiplier (Target = CTC × this)", type: "number", required: true },
      { key: "status", label: "Status", type: "select", options: sel("active", "inactive") },
    ],
  },
  "aum-entries": {
    title: "AUM Entries", endpoint: "aum-entries",
    // Select a customer -> pull that FXArtha client's deposit/withdrawal + RM + business.
    // reset: a different customer overwrites (and clears if the new one has none).
    autofill: { endpoint: "reports/customer-fx", trigger: ["customer", "entry_type"],
                fills: ["employee", "business", "amount"], reset: true },
    filters: [
      { key: "employee", label: "Employee", ref: "employees", labelKey: "user_name" },
      { key: "entry_type", label: "Type", options: sel("deposit", "withdrawal") },
    ],
    columns: [
      { key: "employee_name", label: "Employee" },
      { key: "business_name", label: "Business" },
      { key: "customer_name", label: "Customer" },
      { key: "entry_type", label: "Type", badge: true },
      { key: "amount", label: "Amount", money: true },
      { key: "date", label: "Date" },
    ],
    fields: [
      { key: "employee", label: "Employee (RM)", type: "ref", ref: "employees", labelKey: "user_name", required: true },
      { key: "business", label: "Business", type: "ref", ref: "businesses", labelKey: "name" },
      { key: "customer", label: "Customer (optional)", type: "ref", ref: "customers", labelKey: "name" },
      { key: "entry_type", label: "Type", type: "select", options: sel("deposit", "withdrawal") },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "date", label: "Date", type: "date", required: true },
      { key: "note", label: "Note (optional)" },
    ],
  },
  "contribution-entries": {
    title: "Contribution Entries", endpoint: "contribution-entries",
    // Select a customer -> pull that FXArtha client's brokerage/insurance/staking/loss + RM + business.
    // reset: a different customer overwrites (and clears if the new one has none).
    autofill: { endpoint: "reports/customer-fx", trigger: ["customer"],
                fills: ["employee", "business", "deposit", "trading_loss", "brokerage", "insurance", "staking"],
                reset: true },
    filters: [
      { key: "employee", label: "Employee", ref: "employees", labelKey: "user_name" },
      { key: "business", label: "Business", ref: "businesses", labelKey: "name" },
      { key: "date", label: "Date", dateRange: true },
    ],
    totals: ["deposit", "trading_loss", "brokerage", "insurance", "staking", "other"],
    columns: [
      { key: "employee_name", label: "Employee" },
      { key: "customer_name", label: "Customer" },
      { key: "brokerage", label: "Brokerage", money: true },
      { key: "insurance", label: "Insurance", money: true },
      { key: "trading_loss", label: "Trading loss", money: true },
      { key: "date", label: "Date" },
    ],
    fields: [
      { key: "employee", label: "Employee (RM)", type: "ref", ref: "employees", labelKey: "user_name", required: true },
      { key: "customer", label: "Customer (optional)", type: "ref", ref: "customers", labelKey: "name" },
      { key: "business", label: "Business (optional)", type: "ref", ref: "businesses", labelKey: "name" },
      { key: "deposit", label: "Deposit", type: "number" },
      { key: "trading_loss", label: "Trading loss", type: "number" },
      { key: "brokerage", label: "Brokerage revenue", type: "number" },
      { key: "insurance", label: "Insurance revenue", type: "number" },
      { key: "staking", label: "Staking revenue", type: "number" },
      { key: "other", label: "Other revenue", type: "number" },
      { key: "date", label: "Date", type: "date", required: true },
    ],
  },
  "contribution-weights": {
    title: "Contribution Formula", endpoint: "contribution-weights", single: true,
    columns: [
      { key: "brokerage", label: "Brokerage ×" },
      { key: "insurance", label: "Insurance ×" },
      { key: "staking", label: "Staking ×" },
      { key: "other", label: "Other ×" },
      { key: "trading_loss", label: "Trading loss ×" },
      { key: "deposit", label: "Deposit ×" },
    ],
    fields: [
      { key: "brokerage", label: "Brokerage weight", type: "number", required: true },
      { key: "insurance", label: "Insurance weight", type: "number", required: true },
      { key: "staking", label: "Staking weight", type: "number", required: true },
      { key: "other", label: "Other revenue weight", type: "number", required: true },
      { key: "trading_loss", label: "Trading loss weight (usually −1)", type: "number", required: true },
      { key: "deposit", label: "Deposit weight (usually 0)", type: "number", required: true },
    ],
  },
  "incentive-slabs": {
    title: "Incentive Slabs", endpoint: "incentive-slabs",
    columns: [
      { key: "min_pct", label: "From %" },
      { key: "max_pct", label: "To % (blank = ∞)" },
      { key: "incentive_pct", label: "Incentive %" },
      { key: "basis", label: "Basis", badge: true },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "name", label: "Tier name (optional)" },
      { key: "min_pct", label: "Attainment from % (>=)", type: "number", required: true },
      { key: "max_pct", label: "Attainment to % (<) — blank = unlimited", type: "number" },
      { key: "incentive_pct", label: "Incentive %", type: "number", required: true },
      { key: "basis", label: "Percent of", type: "select", options: [
        { value: "revenue", label: "Revenue generated" },
        { value: "target", label: "Target value" },
      ] },
      { key: "status", label: "Status", type: "select", options: sel("active", "inactive") },
    ],
  },
  "activity-incentives": {
    title: "Activity Incentives", endpoint: "activity-incentives",
    columns: [
      { key: "name", label: "Reward" },
      { key: "metric_name", label: "KPI" },
      { key: "rate", label: "Rate (per unit)", money: true },
      { key: "min_count", label: "Min count" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "name", label: "Reward name (e.g. Lots reward, Meeting bonus)", required: true },
      { key: "metric", label: "KPI metric", type: "ref", ref: "metric-definitions", labelKey: "name", required: true },
      { key: "rate", label: "Amount per unit", type: "number", required: true },
      { key: "min_count", label: "Only pay if value reaches (min count)", type: "number" },
      { key: "status", label: "Status", type: "select", options: sel("active", "inactive") },
    ],
  },
  "performance-weights": {
    title: "Performance Weights", endpoint: "performance-weights",
    columns: [
      { key: "label", label: "Applies to" },
      { key: "revenue_weight", label: "Revenue %" },
      { key: "growth_weight", label: "Growth %" },
      { key: "activity_weight", label: "Activity %" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "scope", label: "Scope", type: "select", options: sel("global", "level"), required: true },
      { key: "hierarchy_level", label: "Hierarchy level (if scope = level)", type: "ref", ref: "hierarchy-levels", labelKey: "level_name" },
      { key: "revenue_weight", label: "Revenue weight", type: "number", required: true },
      { key: "growth_weight", label: "Growth weight", type: "number", required: true },
      { key: "activity_weight", label: "Activity weight", type: "number", required: true },
      { key: "status", label: "Status", type: "select", options: sel("active", "inactive") },
    ],
  },
  expenses: {
    title: "Expenses", endpoint: "expenses",
    columns: [
      { key: "expense_type", label: "Type" },
      { key: "department_name", label: "Department" },
      { key: "amount", label: "Amount", money: true },
      { key: "date", label: "Date" },
    ],
    fields: [
      { key: "expense_type", label: "Type", required: true },
      { key: "department", label: "Department", type: "ref", ref: "departments", labelKey: "department_name" },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "date", label: "Date", type: "date", required: true },
    ],
  },
  commissions: {
    title: "Commissions", endpoint: "commissions", search: true,
    columns: [
      { key: "partner_name", label: "Partner" },
      { key: "business_name", label: "Business" },
      { key: "amount", label: "Amount", money: true },
      { key: "date", label: "Date" },
    ],
    fields: [
      { key: "partner_name", label: "Partner name", required: true },
      { key: "business", label: "Business", type: "ref", ref: "businesses", labelKey: "name" },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "date", label: "Date", type: "date", required: true },
    ],
  },
};
