// Single source of truth for every CRUD module.
// `columns` -> table; `fields` -> create/edit form.
// field types: text, number, email, date, datetime-local, textarea, select, ref
// ref fields load options from another endpoint (labelKey shown to user).

export const STATUS_COLORS = {
  active: "bg-emerald-50 text-emerald-700",
  inactive: "bg-ink-100 text-ink-600",
  new: "bg-blue-50 text-blue-700",
  contacted: "bg-amber-50 text-amber-700",
  qualified: "bg-violet-50 text-violet-700",
  converted: "bg-emerald-50 text-emerald-700",
  lost: "bg-rose-50 text-rose-700",
  won: "bg-emerald-50 text-emerald-700",
  open: "bg-blue-50 text-blue-700",
  closed: "bg-ink-100 text-ink-600",
  proposal: "bg-amber-50 text-amber-700",
  negotiation: "bg-violet-50 text-violet-700",
  pending: "bg-amber-50 text-amber-700",
  approved: "bg-emerald-50 text-emerald-700",
  rejected: "bg-rose-50 text-rose-700",
  resolved: "bg-emerald-50 text-emerald-700",
  assigned: "bg-blue-50 text-blue-700",
  in_progress: "bg-violet-50 text-violet-700",
  present: "bg-emerald-50 text-emerald-700",
  absent: "bg-rose-50 text-rose-700",
  urgent: "bg-rose-50 text-rose-700",
  high: "bg-amber-50 text-amber-700",
  medium: "bg-blue-50 text-blue-700",
  low: "bg-ink-100 text-ink-600",
};

const sel = (...opts) => opts.map((o) => ({ value: o, label: o[0].toUpperCase() + o.slice(1).replace("_", " ") }));

export const RESOURCES = {
  users: {
    title: "Users", endpoint: "users", search: true,
    columns: [
      { key: "employee_id", label: "Emp ID" },
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "role_name", label: "Role" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "name", label: "Name", required: true },
      { key: "email", label: "Email", type: "email", required: true },
      { key: "employee_id", label: "Employee ID" },
      { key: "phone", label: "Phone" },
      { key: "role", label: "Role", type: "ref", ref: "roles", labelKey: "name" },
      { key: "status", label: "Status", type: "select", options: sel("active", "inactive", "suspended") },
      { key: "password", label: "Password (set/reset)", type: "text" },
    ],
  },
  roles: {
    title: "Roles", endpoint: "roles",
    columns: [{ key: "name", label: "Role" }, { key: "description", label: "Description" }],
    fields: [{ key: "name", label: "Name", required: true }, { key: "description", label: "Description", type: "textarea" }],
  },
  teams: {
    title: "Teams", endpoint: "teams", search: true,
    columns: [{ key: "name", label: "Team" }, { key: "leader_name", label: "Leader" }],
    fields: [
      { key: "name", label: "Team name", required: true },
      { key: "leader", label: "Leader", type: "ref", ref: "users", labelKey: "name" },
    ],
  },
  businesses: {
    title: "Businesses", endpoint: "businesses", search: true,
    columns: [
      { key: "name", label: "Business" },
      { key: "description", label: "Description" },
      { key: "product_count", label: "Products" },
    ],
    fields: [
      { key: "name", label: "Business name", required: true },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },
  products: {
    title: "Products", endpoint: "products", search: true,
    columns: [
      { key: "name", label: "Product" },
      { key: "business_name", label: "Business" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "name", label: "Product name", required: true },
      { key: "business", label: "Business", type: "ref", ref: "businesses", labelKey: "name", required: true },
      { key: "status", label: "Status", type: "select", options: sel("active", "inactive") },
    ],
  },
  "lead-sources": {
    title: "Lead Sources", endpoint: "lead-sources",
    columns: [{ key: "name", label: "Source" }],
    fields: [{ key: "name", label: "Source name", required: true }],
  },
  leads: {
    title: "Leads", endpoint: "leads", search: true, importable: true, detailPath: "/leads",
    distribute: { path: "leads/distribute" },
    filters: [
      { key: "status", label: "Status", options: sel("new", "contacted", "qualified", "converted", "lost") },
      { key: "source", label: "Source", ref: "lead-sources", labelKey: "name" },
    ],
    columns: [
      { key: "lead_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "phone", label: "Phone" },
      { key: "country", label: "Country" },
      { key: "source_name", label: "Source" },
      { key: "assigned_name", label: "Owner" },
      { key: "score", label: "Score", score: true },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "lead_code", label: "Lead code", required: true },
      { key: "name", label: "Name", required: true },
      { key: "email", label: "Email", type: "email" },
      { key: "phone", label: "Phone" },
      { key: "country", label: "Country" },
      { key: "source", label: "Source", type: "ref", ref: "lead-sources", labelKey: "name" },
      { key: "assigned_to", label: "Assign to", type: "ref", ref: "users", labelKey: "name" },
      { key: "status", label: "Status", type: "select", options: sel("new", "contacted", "qualified", "converted", "lost") },
    ],
  },
  "lead-activities": {
    title: "Lead Activities", endpoint: "lead-activities", search: false,
    columns: [
      { key: "lead", label: "Lead #" },
      { key: "activity_type", label: "Type", badge: true },
      { key: "remarks", label: "Remarks" },
      { key: "followup_date", label: "Follow-up" },
      { key: "user_name", label: "By" },
    ],
    fields: [
      { key: "lead", label: "Lead", type: "ref", ref: "leads", labelKey: "name", required: true },
      { key: "activity_type", label: "Type", type: "select", options: sel("call", "whatsapp", "email", "meeting", "note") },
      { key: "remarks", label: "Remarks", type: "textarea" },
      { key: "followup_date", label: "Follow-up date", type: "date" },
      { key: "next_action", label: "Next action" },
    ],
  },
  opportunities: {
    title: "Opportunities", endpoint: "opportunities", search: true,
    filters: [
      { key: "stage", label: "Stage", options: sel("proposal", "negotiation", "won", "lost", "active") },
      { key: "status", label: "Status", options: sel("open", "closed") },
    ],
    columns: [
      { key: "lead_name", label: "Lead" },
      { key: "product_name", label: "Product" },
      { key: "assigned_name", label: "Owner" },
      { key: "stage", label: "Stage", badge: true },
      { key: "expected_revenue", label: "Expected", money: true },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "lead", label: "Lead", type: "ref", ref: "leads", labelKey: "name", required: true },
      { key: "product", label: "Product", type: "ref", ref: "products", labelKey: "name" },
      { key: "assigned_to", label: "Owner", type: "ref", ref: "users", labelKey: "name" },
      { key: "stage", label: "Stage", type: "select", options: sel("proposal", "negotiation", "won", "lost", "active") },
      { key: "expected_revenue", label: "Expected revenue", type: "number" },
      { key: "status", label: "Status", type: "select", options: sel("open", "closed") },
    ],
  },
  customers: {
    title: "Customers", endpoint: "customers", search: true, detailPath: "/customers",
    columns: [
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "country", label: "Country" },
    ],
    fields: [
      { key: "name", label: "Name", required: true },
      { key: "email", label: "Email", type: "email" },
      { key: "phone", label: "Phone" },
      { key: "country", label: "Country" },
    ],
  },
  communications: {
    title: "Communications", endpoint: "communications",
    columns: [
      { key: "channel", label: "Channel", badge: true },
      { key: "direction", label: "Direction" },
      { key: "message", label: "Message" },
      { key: "created_at", label: "When", datetime: true },
    ],
    fields: [
      { key: "channel", label: "Channel", type: "select", options: sel("whatsapp", "email", "sms", "telegram") },
      { key: "direction", label: "Direction", type: "select", options: sel("outbound", "inbound") },
      { key: "lead", label: "Lead", type: "ref", ref: "leads", labelKey: "name" },
      { key: "customer", label: "Customer", type: "ref", ref: "customers", labelKey: "name" },
      { key: "message", label: "Message", type: "textarea" },
    ],
  },
  targets: {
    title: "Targets", endpoint: "targets", search: true,
    filters: [
      { key: "target_type", label: "Type", options: sel("revenue", "leads", "conversions") },
    ],
    columns: [
      { key: "name", label: "Target" },
      { key: "target_type", label: "Type", badge: true },
      { key: "value", label: "Target", money: true },
      { key: "achieved", label: "Achieved", money: true },
      { key: "progress_pct", label: "Progress", progress: true },
      { key: "business_name", label: "Business" },
      { key: "end_date", label: "Ends" },
    ],
    fields: [
      { key: "name", label: "Target name", required: true },
      { key: "target_type", label: "Type", type: "select", options: sel("revenue", "leads", "conversions") },
      { key: "value", label: "Value", type: "number" },
      { key: "business", label: "Business", type: "ref", ref: "businesses", labelKey: "name" },
      { key: "start_date", label: "Start date", type: "date", required: true },
      { key: "end_date", label: "End date", type: "date", required: true },
    ],
  },
  revenues: {
    title: "Revenue", endpoint: "revenues", search: true,
    columns: [
      { key: "customer_name", label: "Customer" },
      { key: "business_name", label: "Business" },
      { key: "gross_revenue", label: "Gross", money: true },
      { key: "commission", label: "Commission", money: true },
      { key: "net_revenue", label: "Net", money: true },
      { key: "created_at", label: "Date", datetime: true },
    ],
    fields: [
      { key: "customer", label: "Customer", type: "ref", ref: "customers", labelKey: "name", required: true },
      { key: "business", label: "Business", type: "ref", ref: "businesses", labelKey: "name" },
      { key: "product", label: "Product", type: "ref", ref: "products", labelKey: "name" },
      { key: "gross_revenue", label: "Gross revenue", type: "number", required: true },
      { key: "commission", label: "Commission", type: "number" },
    ],
  },
  tickets: {
    title: "Support Tickets", endpoint: "tickets", search: true, detailPath: "/tickets",
    filters: [
      { key: "status", label: "Status", options: sel("open", "assigned", "in_progress", "resolved", "closed") },
      { key: "priority", label: "Priority", options: sel("low", "medium", "high", "urgent") },
    ],
    columns: [
      { key: "ticket_no", label: "Ticket #" },
      { key: "customer_name", label: "Customer" },
      { key: "category", label: "Category" },
      { key: "priority", label: "Priority", badge: true },
      { key: "assigned_name", label: "Agent" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "ticket_no", label: "Ticket no", required: true },
      { key: "customer", label: "Customer", type: "ref", ref: "customers", labelKey: "name" },
      { key: "category", label: "Category" },
      { key: "priority", label: "Priority", type: "select", options: sel("low", "medium", "high", "urgent") },
      { key: "assigned_to", label: "Agent", type: "ref", ref: "users", labelKey: "name" },
      { key: "status", label: "Status", type: "select", options: sel("open", "assigned", "in_progress", "resolved", "closed") },
    ],
  },
  departments: {
    title: "Departments", endpoint: "departments",
    columns: [{ key: "department_name", label: "Department" }],
    fields: [{ key: "department_name", label: "Department name", required: true }],
  },
  employees: {
    title: "Employees", endpoint: "employees", search: true,
    columns: [
      { key: "user_name", label: "Name" },
      { key: "designation", label: "Designation" },
      { key: "department_name", label: "Department" },
      { key: "salary", label: "Salary", money: true },
      { key: "joining_date", label: "Joined" },
    ],
    fields: [
      { key: "user", label: "User", type: "ref", ref: "users", labelKey: "name", required: true },
      { key: "department", label: "Department", type: "ref", ref: "departments", labelKey: "department_name" },
      { key: "designation", label: "Designation" },
      { key: "salary", label: "Salary", type: "number" },
      { key: "joining_date", label: "Joining date", type: "date" },
    ],
  },
  attendance: {
    title: "Attendance", endpoint: "attendance",
    columns: [
      { key: "employee_name", label: "Employee" },
      { key: "date", label: "Date" },
      { key: "working_hours", label: "Hours" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "employee", label: "Employee", type: "ref", ref: "employees", labelKey: "user_name", required: true },
      { key: "date", label: "Date", type: "date", required: true },
      { key: "working_hours", label: "Working hours", type: "number" },
      { key: "status", label: "Status", type: "select", options: sel("present", "absent", "half_day", "leave") },
    ],
  },
  "employee-activities": {
    title: "Employee Activity", endpoint: "employee-activities",
    columns: [
      { key: "employee_name", label: "Employee" },
      { key: "date", label: "Date" },
      { key: "active_duration", label: "Active (min)" },
      { key: "calls_completed", label: "Calls" },
      { key: "tickets_updated", label: "Tickets" },
    ],
    fields: [
      { key: "employee", label: "Employee", type: "ref", ref: "employees", labelKey: "user_name", required: true },
      { key: "date", label: "Date", type: "date", required: true },
      { key: "login_duration", label: "Login (min)", type: "number" },
      { key: "active_duration", label: "Active (min)", type: "number" },
      { key: "idle_duration", label: "Idle (min)", type: "number" },
      { key: "calls_completed", label: "Calls", type: "number" },
      { key: "tickets_updated", label: "Tickets updated", type: "number" },
    ],
  },
  "leave-types": {
    title: "Leave Types", endpoint: "leave-types",
    columns: [{ key: "leave_name", label: "Leave type" }],
    fields: [{ key: "leave_name", label: "Leave type", required: true }],
  },
  leaves: {
    title: "Leaves", endpoint: "leaves",
    filters: [
      { key: "status", label: "Status", options: sel("pending", "approved", "rejected") },
    ],
    rowActions: [
      { label: "Approve", icon: "check", variant: "success", when: { status: "pending" }, post: (id) => `leaves/${id}/approve/` },
      { label: "Reject", icon: "x", variant: "danger", when: { status: "pending" }, post: (id) => `leaves/${id}/reject/` },
    ],
    columns: [
      { key: "employee_name", label: "Employee" },
      { key: "start_date", label: "From" },
      { key: "end_date", label: "To" },
      { key: "reason", label: "Reason" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { key: "employee", label: "Employee", type: "ref", ref: "employees", labelKey: "user_name", required: true },
      { key: "leave_type", label: "Leave type", type: "ref", ref: "leave-types", labelKey: "leave_name" },
      { key: "start_date", label: "From", type: "date", required: true },
      { key: "end_date", label: "To", type: "date", required: true },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: sel("pending", "approved", "rejected") },
    ],
  },
  payrolls: {
    title: "Payroll", endpoint: "payrolls",
    rowActions: [
      { label: "Payslip", icon: "download", variant: "info", download: (id) => `payrolls/${id}/payslip/` },
    ],
    columns: [
      { key: "employee_name", label: "Employee" },
      { key: "basic_salary", label: "Basic", money: true },
      { key: "incentive", label: "Incentive", money: true },
      { key: "bonus", label: "Bonus", money: true },
      { key: "deduction", label: "Deduction", money: true },
      { key: "final_salary", label: "Net Pay", money: true },
      { key: "month", label: "Month" },
      { key: "year", label: "Year" },
    ],
    fields: [
      { key: "employee", label: "Employee", type: "ref", ref: "employees", labelKey: "user_name", required: true },
      { key: "basic_salary", label: "Basic salary", type: "number" },
      { key: "incentive", label: "Incentive", type: "number" },
      { key: "bonus", label: "Bonus", type: "number" },
      { key: "deduction", label: "Deduction", type: "number" },
      { key: "month", label: "Month (1-12)", type: "number", required: true },
      { key: "year", label: "Year", type: "number", required: true },
    ],
  },
  "incentive-rules": {
    title: "Incentive Rules", endpoint: "incentive-rules",
    columns: [
      { key: "business", label: "Business #" },
      { key: "formula_type", label: "Type", badge: true },
      { key: "formula_value", label: "Value" },
    ],
    fields: [
      { key: "business", label: "Business", type: "ref", ref: "businesses", labelKey: "name", required: true },
      { key: "product", label: "Product", type: "ref", ref: "products", labelKey: "name" },
      { key: "formula_type", label: "Formula type", type: "select", options: sel("percentage", "fixed", "slab") },
      { key: "formula_value", label: "Value", type: "number" },
    ],
  },
  incentives: {
    title: "Incentives", endpoint: "incentives",
    recalc: { path: "incentives/calculate", title: "Auto-Calculate Incentives" },
    filters: [],
    columns: [
      { key: "employee", label: "Employee #" },
      { key: "amount", label: "Amount", money: true },
      { key: "month", label: "Month" },
      { key: "year", label: "Year" },
    ],
    fields: [
      { key: "employee", label: "Employee", type: "ref", ref: "employees", labelKey: "user_name", required: true },
      { key: "rule", label: "Rule", type: "ref", ref: "incentive-rules", labelKey: "formula_type" },
      { key: "amount", label: "Amount", type: "number" },
      { key: "month", label: "Month (1-12)", type: "number", required: true },
      { key: "year", label: "Year", type: "number", required: true },
    ],
  },
  expenses: {
    title: "Expenses", endpoint: "expenses",
    columns: [
      { key: "expense_type", label: "Type" },
      { key: "department_name", label: "Department" },
      { key: "amount", label: "Amount", money: true },
      { key: "date", label: "Date" },
    ],
    fields: [
      { key: "expense_type", label: "Type", required: true },
      { key: "department", label: "Department", type: "ref", ref: "departments", labelKey: "department_name" },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "date", label: "Date", type: "date", required: true },
    ],
  },
  commissions: {
    title: "Commissions", endpoint: "commissions", search: true,
    columns: [
      { key: "partner_name", label: "Partner" },
      { key: "business_name", label: "Business" },
      { key: "amount", label: "Amount", money: true },
      { key: "date", label: "Date" },
    ],
    fields: [
      { key: "partner_name", label: "Partner name", required: true },
      { key: "business", label: "Business", type: "ref", ref: "businesses", labelKey: "name" },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "date", label: "Date", type: "date", required: true },
    ],
  },
};
