# Generated by Django 5.0.6 on 2026-07-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_assign_targets_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('workdays_per_month', models.PositiveIntegerField(default=22)),
                ('default_incentive_rate', models.DecimalField(decimal_places=4, default=0.03, max_digits=6)),
                ('training_pass_mark', models.DecimalField(decimal_places=2, default=0.8, max_digits=5)),
                ('first_contact_sla_min', models.PositiveIntegerField(default=15)),
                ('company_health_target', models.DecimalField(decimal_places=2, default=0.85, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
