# Generated by Django 5.0.6 on 2026-07-03 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_lead_business'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconnection',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='crm.business'),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='platform',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='integrationconnection',
            unique_together={('platform', 'business')},
        ),
    ]
