# Generated by Django 5.0.6 on 2026-07-17 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_customer_assigned_to'),
        ('integrations', '0002_integrationconnection_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DagChainNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('validator', 'Validator'), ('storage', 'Storage')], max_length=12)),
                ('node_key', models.CharField(blank=True, max_length=80)),
                ('package', models.CharField(blank=True, max_length=80)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('payment_status', models.CharField(blank=True, max_length=30)),
                ('uptime', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('blocks_validated', models.PositiveIntegerField(default=0)),
                ('rewards_earned', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('pending_rewards', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('claimed_rewards', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('effective_apy', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('capacity', models.CharField(blank=True, max_length=40)),
                ('is_staked', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dagchain_nodes', to='crm.customer')),
            ],
            options={
                'ordering': ['-purchase_price'],
            },
        ),
        migrations.CreateModel(
            name='DagChainProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('wallet_address', models.CharField(blank=True, max_length=90)),
                ('user_type', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('email_verified', models.BooleanField(default=False)),
                ('kyc_status', models.CharField(blank=True, max_length=30)),
                ('social_provider', models.CharField(blank=True, max_length=30)),
                ('dgc_balance', models.DecimalField(decimal_places=6, default=0, max_digits=22)),
                ('fuel_wallet_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('referral_code', models.CharField(blank=True, max_length=40)),
                ('referral_count', models.PositiveIntegerField(default=0)),
                ('total_referral_earnings', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('validator_nodes_count', models.PositiveIntegerField(default=0)),
                ('storage_nodes_count', models.PositiveIntegerField(default=0)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dagchain', to='crm.customer')),
            ],
            options={
                'ordering': ['-total_referral_earnings', '-dgc_balance'],
            },
        ),
    ]
