# Generated by Django 5.0.6 on 2026-07-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_dagchainnode_staking'),
    ]

    operations = [
        migrations.CreateModel(
            name='DagChainCommissionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validator_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('storage_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('staking_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
