# Generated by Django 5.0.6 on 2026-07-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_dagchaincommissionrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dagchainprofile',
            name='staked_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=22),
        ),
        migrations.AddField(
            model_name='dagchainprofile',
            name='staked_stakes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
