# Generated by Django 5.0.6 on 2026-07-24 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_role_derived_levels'),
        ('integrations', '0006_dagchainprofile_staked_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('fxartha', 'FX Artha'), ('dagchain', 'DAGChain')], max_length=20)),
                ('product_key', models.CharField(max_length=120)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='hr.employee')),
            ],
            options={
                'unique_together': {('platform', 'product_key', 'employee')},
            },
        ),
    ]
