# Generated by Django 5.0.6 on 2026-07-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_commissionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrule',
            name='basis',
            field=models.CharField(choices=[('percent', 'Percent'), ('amount', 'Flat amount')], default='percent', max_length=10),
        ),
    ]
