# Generated by Django 5.0.6 on 2026-06-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('proposal', 'Proposal')], default='call', max_length=20),
        ),
    ]
