# Generated by Django 5.0.6 on 2026-06-23 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_proposal_proposalitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.business'),
        ),
    ]
