# Generated by Django 5.0.6 on 2026-06-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_proposal_accepted_at_proposal_discount_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='revenue_type',
            field=models.CharField(choices=[('one_time', 'One-Time Sale'), ('recurring', 'Recurring / Subscription'), ('per_unit', 'Per Unit'), ('token', 'Token Purchase')], default='one_time', max_length=20),
        ),
    ]
