# Generated by Django 5.0.6 on 2026-06-30 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_business_status_product_price_product_product_type_and_more'),
        ('hr', '0009_seed_target_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('key', models.SlugField(blank=True, max_length=140, unique=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('aggregation', models.CharField(choices=[('sum', 'Sum'), ('count', 'Count'), ('average', 'Average'), ('latest', 'Latest')], default='sum', max_length=20)),
                ('category', models.CharField(choices=[('growth', 'Growth'), ('activity', 'Activity'), ('other', 'Other')], default='activity', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('derived', 'Derived from CRM data')], default='manual', max_length=20)),
                ('derived_key', models.CharField(blank=True, choices=[('', '—'), ('lead_activity:meeting', 'Meetings logged (Lead Activity)'), ('lead_activity:call', 'Calls logged (Lead Activity)'), ('lead:converted', 'Leads converted')], default='', max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='crm.business')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.product')),
            ],
        ),
        migrations.CreateModel(
            name='MetricEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_entries', to='hr.employee')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.lead')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='crm.metricdefinition')),
            ],
            options={
                'verbose_name_plural': 'Metric entries',
                'ordering': ['-date'],
            },
        ),
    ]
