# Generated by Django 5.0.6 on 2026-06-30 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_seed_metrics'),
        ('hr', '0015_seed_formula_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('trading_loss', models.DecimalField(decimal_places=2, default=-1, max_digits=6)),
                ('brokerage', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('insurance', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('staking', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('other', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='AumEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default='deposit', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aum_entries', to='hr.employee')),
            ],
            options={
                'verbose_name_plural': 'AUM entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContributionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('trading_loss', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('brokerage', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('staking', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('other', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('date', models.DateField()),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='hr.employee')),
            ],
            options={
                'verbose_name_plural': 'Contribution entries',
                'ordering': ['-date'],
            },
        ),
    ]
