# Generated by Django 5.0.6 on 2026-07-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_seed_contribution_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='aumentry',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customer',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
