# Generated by Django 5.0.6 on 2026-07-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_aumentry_external_id_customer_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
