# Generated by Django 5.0.6 on 2026-07-01 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_lead_converted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aumentry',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.business'),
        ),
    ]
