# Generated by Django 5.0.6 on 2026-07-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_aumentry_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionentry',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='metricentry',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
