# Generated by Django 5.0.6 on 2026-07-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_seed_lead_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivity',
            name='duration_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='meeting_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='meeting_status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], max_length=20),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='outcome',
            field=models.CharField(blank=True, choices=[('connected', 'Connected'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('voicemail', 'Voicemail'), ('wrong_number', 'Wrong Number'), ('interested', 'Interested'), ('callback', 'Callback Requested'), ('meeting_booked', 'Meeting Booked'), ('not_interested', 'Not Interested'), ('converted', 'Converted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('attempted', 'Attempted'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('meeting_booked', 'Meeting Booked'), ('meeting_done', 'Meeting Done'), ('negotiation', 'Negotiation'), ('converted', 'Closed Won'), ('lost', 'Closed Lost'), ('nurture', 'Nurture')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Call'), ('outbound_call', 'Outbound Call'), ('inbound_call', 'Inbound Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('callback', 'Callback'), ('followup', 'Follow-up'), ('meeting', 'Meeting'), ('document_collection', 'Document Collection'), ('service_call', 'Service Call'), ('note', 'Note')], default='call', max_length=20),
        ),
    ]
