# Generated by Django 5.0.6 on 2026-07-27 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_leadactivity_duration_min_leadactivity_meeting_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='probability',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PostSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_date', models.DateField(blank=True, null=True)),
                ('sale_type', models.CharField(choices=[('new', 'New'), ('renewal', 'Renewal'), ('topup', 'Top-up')], default='new', max_length=10)),
                ('sale_status', models.CharField(choices=[('closed_won', 'Closed Won'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='closed_won', max_length=15)),
                ('gross_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('collected_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('direct_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('welcome_call', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=10)),
                ('documents_complete', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('service_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('churned', 'Churned')], default='active', max_length=10)),
                ('next_renewal_date', models.DateField(blank=True, null=True)),
                ('topup_opportunity', models.BooleanField(default=False)),
                ('topup_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('referral_received', models.BooleanField(default=False)),
                ('post_sales_health', models.CharField(choices=[('healthy', 'Healthy'), ('at_risk', 'At Risk'), ('churned', 'Churned')], default='healthy', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='crm.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='crm.lead')),
                ('onboarding_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_sales', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.product')),
            ],
            options={
                'ordering': ['-close_date', '-id'],
            },
        ),
    ]
