# Generated by Django 5.0.6 on 2026-07-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_postsale_and_lead_register_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivity',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='direction',
            field=models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=10),
        ),
    ]
