# Generated by Django 5.0.6 on 2026-07-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_leadactivity_direction_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
