# Generated by Django 5.0.6 on 2026-07-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_lead_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='account_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='metricdefinition',
            name='derived_key',
            field=models.CharField(blank=True, choices=[('', '—'), ('lead_activity:meeting', 'Meetings logged (Lead Activity)'), ('lead_activity:call', 'Calls logged (Lead Activity)'), ('lead:converted', 'Leads converted'), ('lead:received', 'Leads received (assigned)'), ('fxartha:deposits', 'FX Artha deposits ($)'), ('dagchain:nodes', 'DAGChain node purchases'), ('revenue', 'Revenue ($, net)'), ('training:completed', 'Training modules completed')], default='', max_length=40),
        ),
    ]
