# Generated by Django 5.0.6 on 2026-07-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
